/**
 * Country Economy Configuration Framework
 * Centralized registry for all country-specific economic parameters.
 * Designed for modular expansion (construction, utilities, taxes, tariffs, shipping, etc.).
 */

const countryEconomy = {
  countries: {
    'India': {
      currency: 'INR',
      employees: {
        'Farmer': 18000,
        'Labourer': 16000,
        'Engineer': 55000,
        'Manager': 75000,
        'Chef': 30000,
        'Fashion Designer': 45000
      },
      commodities: {
        'seeds': { name: 'Seeds', price: 5.00, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Wheat', 'Rice', 'Cotton', 'Grains', 'Vegetables'] },
        'water': { name: 'Water', price: 2.00, category: 'Agriculture', producedBy: 'Government', usedIn: ['Seeds', 'Wheat', 'Rice', 'Cotton', 'Grains', 'Vegetables', 'Milk', 'Eggs'] },
        'wheat': { name: 'Wheat', price: 90.00, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Bread', 'Biscuits'] },
        'rice': { name: 'Rice', price: 80.00, category: 'Agriculture', producedBy: 'Farming', usedIn: [] },
        'cotton': { name: 'Cotton', price: 100.00, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Shirts', 'Jeans', 'Jackets'] },
        'milk': { name: 'Milk', price: 39.00, category: 'Agriculture', producedBy: 'Dairy', usedIn: ['Biscuits', 'Cheese'] },
        'coal': { name: 'Coal', price: 350.00, category: 'Mining', producedBy: 'Mining', usedIn: ['Cement', 'Bricks', 'Steel Beams', 'Phones', 'Laptops', 'TVs', 'Cars'] },
        'grains': { name: 'Grains', price: 12.00, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Fodder', 'Eggs'] },
        'vegetables': { name: 'Vegetables', price: 20.00, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Fodder'] },
        'fodder': { name: 'Fodder', price: 18.00, category: 'Agriculture', producedBy: 'Dairy', usedIn: ['Milk'] },
        'eggs': { name: 'Eggs', price: 25.00, category: 'Agriculture', producedBy: 'Dairy', usedIn: [] },
        'iron_ore': { name: 'Iron Ore', price: 300.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'bauxite_ore': { name: 'Bauxite Ore', price: 320.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'limestone': { name: 'Limestone', price: 180.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'gypsum': { name: 'Gypsum', price: 200.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'crude_oil': { name: 'Crude Oil', price: 450.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'minerals': { name: 'Minerals', price: 400.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'sand': { name: 'Sand', price: 100.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'clay': { name: 'Clay', price: 120.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'energy': { name: 'Energy', price: 12.00, category: 'Utilities', producedBy: 'Government', usedIn: ['Coal', 'Iron Ore', 'Bauxite Ore', 'Limestone', 'Gypsum', 'Crude Oil', 'Minerals', 'Sand', 'Clay'] },
        'cows': { name: 'Cows', price: 8000.00, category: 'Agriculture', producedBy: 'Government', usedIn: ['Milk'] },
        'hens': { name: 'Hens', price: 400.00, category: 'Agriculture', producedBy: 'Government', usedIn: ['Eggs'] },
        'shirts': { name: 'Shirts', price: 850.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'jeans': { name: 'Jeans', price: 1200.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'jackets': { name: 'Jackets', price: 2000.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'fabric': { name: 'Fabric', price: 350.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'bread': { name: 'Bread', price: 600.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'biscuits': { name: 'Biscuits', price: 550.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'cheese': { name: 'Cheese', price: 900.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'steel': { name: 'Steel', price: 500.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: ['Steel Beams'] },
        'aluminium': { name: 'Aluminium', price: 520.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'cement': { name: 'Cement', price: 700.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'bricks': { name: 'Bricks', price: 450.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'steel_beams': { name: 'Steel Beams', price: 1800.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: ['Cars'] },
        'glass': { name: 'Glass', price: 180.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'silicon': { name: 'Silicon', price: 220.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'plastics': { name: 'Plastics', price: 600.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'chemicals': { name: 'Chemicals', price: 550.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'processor': { name: 'Processor', price: 1800.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs', 'On-board Computer'] },
        'display': { name: 'Display', price: 2500.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs'] },
        'electronic_components': { name: 'Electronic Components', price: 1500.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs', 'On-board Computer'] },
        'battery': { name: 'Battery', price: 2200.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops'] },
        'on_board_computer': { name: 'On-board Computer', price: 8500.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Cars'] },
        'phones': { name: 'Phones', price: 18000.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'laptops': { name: 'Laptops', price: 48000.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'tvs': { name: 'TVs', price: 32000.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'combustion_engine': { name: 'Combustion Engine', price: 14000.00, category: 'Automotive', producedBy: 'Automobile Manufacturing', usedIn: ['Cars'] },
        'cars': { name: 'Cars', price: 650000.00, category: 'Automotive', producedBy: 'Automobile Manufacturing', usedIn: [] }
      },
      construction: {},
      utilities: {},
      taxes: {}
    },
    'United States': {
      currency: 'USD',
      employees: {
        'Farmer': 4000,
        'Labourer': 3600,
        'Engineer': 8500,
        'Manager': 11000,
        'Chef': 4800,
        'Fashion Designer': 7200
      },
      commodities: {
        'seeds': { name: 'Seeds', price: 0.15, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Wheat', 'Rice', 'Cotton', 'Grains', 'Vegetables'] },
        'water': { name: 'Water', price: 0.06, category: 'Agriculture', producedBy: 'Government', usedIn: ['Seeds', 'Wheat', 'Rice', 'Cotton', 'Grains', 'Vegetables', 'Milk', 'Eggs'] },
        'wheat': { name: 'Wheat', price: 2.40, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Bread', 'Biscuits'] },
        'rice': { name: 'Rice', price: 2.10, category: 'Agriculture', producedBy: 'Farming', usedIn: [] },
        'cotton': { name: 'Cotton', price: 2.80, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Shirts', 'Jeans', 'Jackets'] },
        'milk': { name: 'Milk', price: 1.10, category: 'Agriculture', producedBy: 'Dairy', usedIn: ['Biscuits', 'Cheese'] },
        'coal': { name: 'Coal', price: 9.00, category: 'Mining', producedBy: 'Mining', usedIn: ['Cement', 'Bricks', 'Steel Beams', 'Phones', 'Laptops', 'TVs', 'Cars'] },
        'grains': { name: 'Grains', price: 0.30, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Fodder', 'Eggs'] },
        'vegetables': { name: 'Vegetables', price: 0.55, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Fodder'] },
        'fodder': { name: 'Fodder', price: 0.50, category: 'Agriculture', producedBy: 'Dairy', usedIn: ['Milk'] },
        'eggs': { name: 'Eggs', price: 0.70, category: 'Agriculture', producedBy: 'Dairy', usedIn: [] },
        'iron_ore': { name: 'Iron Ore', price: 8.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'bauxite_ore': { name: 'Bauxite Ore', price: 8.50, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'limestone': { name: 'Limestone', price: 4.80, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'gypsum': { name: 'Gypsum', price: 5.40, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'crude_oil': { name: 'Crude Oil', price: 12.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'minerals': { name: 'Minerals', price: 10.50, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'sand': { name: 'Sand', price: 2.80, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'clay': { name: 'Clay', price: 3.10, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'energy': { name: 'Energy', price: 0.30, category: 'Utilities', producedBy: 'Government', usedIn: ['Coal', 'Iron Ore', 'Bauxite Ore', 'Limestone', 'Gypsum', 'Crude Oil', 'Minerals', 'Sand', 'Clay'] },
        'cows': { name: 'Cows', price: 220.00, category: 'Agriculture', producedBy: 'Government', usedIn: ['Milk'] },
        'hens': { name: 'Hens', price: 11.00, category: 'Agriculture', producedBy: 'Government', usedIn: ['Eggs'] },
        'shirts': { name: 'Shirts', price: 24.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'jeans': { name: 'Jeans', price: 36.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'jackets': { name: 'Jackets', price: 60.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'fabric': { name: 'Fabric', price: 10.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'bread': { name: 'Bread', price: 16.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'biscuits': { name: 'Biscuits', price: 15.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'cheese': { name: 'Cheese', price: 25.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'steel': { name: 'Steel', price: 14.50, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: ['Steel Beams'] },
        'aluminium': { name: 'Aluminium', price: 15.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'cement': { name: 'Cement', price: 20.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'bricks': { name: 'Bricks', price: 12.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'steel_beams': { name: 'Steel Beams', price: 52.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: ['Cars'] },
        'glass': { name: 'Glass', price: 5.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'silicon': { name: 'Silicon', price: 6.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'plastics': { name: 'Plastics', price: 17.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'chemicals': { name: 'Chemicals', price: 15.50, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'processor': { name: 'Processor', price: 52.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs', 'On-board Computer'] },
        'display': { name: 'Display', price: 72.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs'] },
        'electronic_components': { name: 'Electronic Components', price: 43.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs', 'On-board Computer'] },
        'battery': { name: 'Battery', price: 63.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops'] },
        'on_board_computer': { name: 'On-board Computer', price: 245.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Cars'] },
        'phones': { name: 'Phones', price: 520.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'laptops': { name: 'Laptops', price: 1350.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'tvs': { name: 'TVs', price: 900.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'combustion_engine': { name: 'Combustion Engine', price: 390.00, category: 'Automotive', producedBy: 'Automobile Manufacturing', usedIn: ['Cars'] },
        'cars': { name: 'Cars', price: 18500.00, category: 'Automotive', producedBy: 'Automobile Manufacturing', usedIn: [] }
      },
      construction: {},
      utilities: {},
      taxes: {}
    },
    'United Kingdom': {
      currency: 'GBP',
      employees: {
        'Farmer': 2600,
        'Labourer': 2400,
        'Engineer': 5600,
        'Manager': 7000,
        'Chef': 3200,
        'Fashion Designer': 4800
      },
      commodities: {
        'seeds': { name: 'Seeds', price: 0.12, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Wheat', 'Rice', 'Cotton', 'Grains', 'Vegetables'] },
        'water': { name: 'Water', price: 0.05, category: 'Agriculture', producedBy: 'Government', usedIn: ['Seeds', 'Wheat', 'Rice', 'Cotton', 'Grains', 'Vegetables', 'Milk', 'Eggs'] },
        'wheat': { name: 'Wheat', price: 2.00, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Bread', 'Biscuits'] },
        'rice': { name: 'Rice', price: 1.80, category: 'Agriculture', producedBy: 'Farming', usedIn: [] },
        'cotton': { name: 'Cotton', price: 2.30, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Shirts', 'Jeans', 'Jackets'] },
        'milk': { name: 'Milk', price: 0.90, category: 'Agriculture', producedBy: 'Dairy', usedIn: ['Biscuits', 'Cheese'] },
        'coal': { name: 'Coal', price: 7.50, category: 'Mining', producedBy: 'Mining', usedIn: ['Cement', 'Bricks', 'Steel Beams', 'Phones', 'Laptops', 'TVs', 'Cars'] },
        'grains': { name: 'Grains', price: 0.25, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Fodder', 'Eggs'] },
        'vegetables': { name: 'Vegetables', price: 0.45, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Fodder'] },
        'fodder': { name: 'Fodder', price: 0.40, category: 'Agriculture', producedBy: 'Dairy', usedIn: ['Milk'] },
        'eggs': { name: 'Eggs', price: 0.55, category: 'Agriculture', producedBy: 'Dairy', usedIn: [] },
        'iron_ore': { name: 'Iron Ore', price: 6.80, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'bauxite_ore': { name: 'Bauxite Ore', price: 7.20, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'limestone': { name: 'Limestone', price: 4.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'gypsum': { name: 'Gypsum', price: 4.50, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'crude_oil': { name: 'Crude Oil', price: 10.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'minerals': { name: 'Minerals', price: 9.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'sand': { name: 'Sand', price: 2.30, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'clay': { name: 'Clay', price: 2.60, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'energy': { name: 'Energy', price: 0.25, category: 'Utilities', producedBy: 'Government', usedIn: ['Coal', 'Iron Ore', 'Bauxite Ore', 'Limestone', 'Gypsum', 'Crude Oil', 'Minerals', 'Sand', 'Clay'] },
        'cows': { name: 'Cows', price: 180.00, category: 'Agriculture', producedBy: 'Government', usedIn: ['Milk'] },
        'hens': { name: 'Hens', price: 9.00, category: 'Agriculture', producedBy: 'Government', usedIn: ['Eggs'] },
        'shirts': { name: 'Shirts', price: 20.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'jeans': { name: 'Jeans', price: 30.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'jackets': { name: 'Jackets', price: 50.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'fabric': { name: 'Fabric', price: 8.50, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'bread': { name: 'Bread', price: 13.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'biscuits': { name: 'Biscuits', price: 12.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'cheese': { name: 'Cheese', price: 21.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'steel': { name: 'Steel', price: 12.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: ['Steel Beams'] },
        'aluminium': { name: 'Aluminium', price: 12.50, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'cement': { name: 'Cement', price: 16.50, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'bricks': { name: 'Bricks', price: 10.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'steel_beams': { name: 'Steel Beams', price: 44.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: ['Cars'] },
        'glass': { name: 'Glass', price: 4.20, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'silicon': { name: 'Silicon', price: 5.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'plastics': { name: 'Plastics', price: 14.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'chemicals': { name: 'Chemicals', price: 13.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'processor': { name: 'Processor', price: 43.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs', 'On-board Computer'] },
        'display': { name: 'Display', price: 60.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs'] },
        'electronic_components': { name: 'Electronic Components', price: 36.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs', 'On-board Computer'] },
        'battery': { name: 'Battery', price: 52.50, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops'] },
        'on_board_computer': { name: 'On-board Computer', price: 204.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Cars'] },
        'phones': { name: 'Phones', price: 430.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'laptops': { name: 'Laptops', price: 1120.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'tvs': { name: 'TVs', price: 760.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'combustion_engine': { name: 'Combustion Engine', price: 330.00, category: 'Automotive', producedBy: 'Automobile Manufacturing', usedIn: ['Cars'] },
        'cars': { name: 'Cars', price: 15000.00, category: 'Automotive', producedBy: 'Automobile Manufacturing', usedIn: [] }
      },
      construction: {},
      utilities: {},
      taxes: {}
    },
    'Germany': {
      currency: 'EUR',
      employees: {
        'Farmer': 3000,
        'Labourer': 2800,
        'Engineer': 6200,
        'Manager': 7500,
        'Chef': 3700,
        'Fashion Designer': 5200
      },
      commodities: {
        'seeds': { name: 'Seeds', price: 0.14, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Wheat', 'Rice', 'Cotton', 'Grains', 'Vegetables'] },
        'water': { name: 'Water', price: 0.05, category: 'Agriculture', producedBy: 'Government', usedIn: ['Seeds', 'Wheat', 'Rice', 'Cotton', 'Grains', 'Vegetables', 'Milk', 'Eggs'] },
        'wheat': { name: 'Wheat', price: 2.20, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Bread', 'Biscuits'] },
        'rice': { name: 'Rice', price: 2.00, category: 'Agriculture', producedBy: 'Farming', usedIn: [] },
        'cotton': { name: 'Cotton', price: 2.50, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Shirts', 'Jeans', 'Jackets'] },
        'milk': { name: 'Milk', price: 1.00, category: 'Agriculture', producedBy: 'Dairy', usedIn: ['Biscuits', 'Cheese'] },
        'coal': { name: 'Coal', price: 8.00, category: 'Mining', producedBy: 'Mining', usedIn: ['Cement', 'Bricks', 'Steel Beams', 'Phones', 'Laptops', 'TVs', 'Cars'] },
        'grains': { name: 'Grains', price: 0.28, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Fodder', 'Eggs'] },
        'vegetables': { name: 'Vegetables', price: 0.50, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Fodder'] },
        'fodder': { name: 'Fodder', price: 0.45, category: 'Agriculture', producedBy: 'Dairy', usedIn: ['Milk'] },
        'eggs': { name: 'Eggs', price: 0.60, category: 'Agriculture', producedBy: 'Dairy', usedIn: [] },
        'iron_ore': { name: 'Iron Ore', price: 7.50, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'bauxite_ore': { name: 'Bauxite Ore', price: 8.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'limestone': { name: 'Limestone', price: 4.50, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'gypsum': { name: 'Gypsum', price: 5.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'crude_oil': { name: 'Crude Oil', price: 11.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'minerals': { name: 'Minerals', price: 10.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'sand': { name: 'Sand', price: 2.50, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'clay': { name: 'Clay', price: 2.80, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'energy': { name: 'Energy', price: 0.28, category: 'Utilities', producedBy: 'Government', usedIn: ['Coal', 'Iron Ore', 'Bauxite Ore', 'Limestone', 'Gypsum', 'Crude Oil', 'Minerals', 'Sand', 'Clay'] },
        'cows': { name: 'Cows', price: 200.00, category: 'Agriculture', producedBy: 'Government', usedIn: ['Milk'] },
        'hens': { name: 'Hens', price: 10.00, category: 'Agriculture', producedBy: 'Government', usedIn: ['Eggs'] },
        'shirts': { name: 'Shirts', price: 22.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'jeans': { name: 'Jeans', price: 33.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'jackets': { name: 'Jackets', price: 55.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'fabric': { name: 'Fabric', price: 9.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'bread': { name: 'Bread', price: 15.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'biscuits': { name: 'Biscuits', price: 14.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'cheese': { name: 'Cheese', price: 23.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'steel': { name: 'Steel', price: 13.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: ['Steel Beams'] },
        'aluminium': { name: 'Aluminium', price: 13.50, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'cement': { name: 'Cement', price: 18.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'bricks': { name: 'Bricks', price: 11.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'steel_beams': { name: 'Steel Beams', price: 48.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: ['Cars'] },
        'glass': { name: 'Glass', price: 4.50, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'silicon': { name: 'Silicon', price: 5.50, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'plastics': { name: 'Plastics', price: 15.50, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'chemicals': { name: 'Chemicals', price: 14.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'processor': { name: 'Processor', price: 46.50, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs', 'On-board Computer'] },
        'display': { name: 'Display', price: 65.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs'] },
        'electronic_components': { name: 'Electronic Components', price: 39.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs', 'On-board Computer'] },
        'battery': { name: 'Battery', price: 57.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops'] },
        'on_board_computer': { name: 'On-board Computer', price: 220.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Cars'] },
        'phones': { name: 'Phones', price: 470.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'laptops': { name: 'Laptops', price: 1220.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'tvs': { name: 'TVs', price: 820.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'combustion_engine': { name: 'Combustion Engine', price: 350.00, category: 'Automotive', producedBy: 'Automobile Manufacturing', usedIn: ['Cars'] },
        'cars': { name: 'Cars', price: 16500.00, category: 'Automotive', producedBy: 'Automobile Manufacturing', usedIn: [] }
      },
      construction: {},
      utilities: {},
      taxes: {}
    },
    'Brazil': {
      currency: 'BRL',
      employees: {
        'Farmer': 5500,
        'Labourer': 5000,
        'Engineer': 11000,
        'Manager': 16000,
        'Chef': 6800,
        'Fashion Designer': 10000
      },
      commodities: {
        'seeds': { name: 'Seeds', price: 0.40, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Wheat', 'Rice', 'Cotton', 'Grains', 'Vegetables'] },
        'water': { name: 'Water', price: 0.15, category: 'Agriculture', producedBy: 'Government', usedIn: ['Seeds', 'Wheat', 'Rice', 'Cotton', 'Grains', 'Vegetables', 'Milk', 'Eggs'] },
        'wheat': { name: 'Wheat', price: 7.00, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Bread', 'Biscuits'] },
        'rice': { name: 'Rice', price: 6.00, category: 'Agriculture', producedBy: 'Farming', usedIn: [] },
        'cotton': { name: 'Cotton', price: 8.00, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Shirts', 'Jeans', 'Jackets'] },
        'milk': { name: 'Milk', price: 3.00, category: 'Agriculture', producedBy: 'Dairy', usedIn: ['Biscuits', 'Cheese'] },
        'coal': { name: 'Coal', price: 28.00, category: 'Mining', producedBy: 'Mining', usedIn: ['Cement', 'Bricks', 'Steel Beams', 'Phones', 'Laptops', 'TVs', 'Cars'] },
        'grains': { name: 'Grains', price: 0.90, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Fodder', 'Eggs'] },
        'vegetables': { name: 'Vegetables', price: 1.50, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Fodder'] },
        'fodder': { name: 'Fodder', price: 1.35, category: 'Agriculture', producedBy: 'Dairy', usedIn: ['Milk'] },
        'eggs': { name: 'Eggs', price: 1.95, category: 'Agriculture', producedBy: 'Dairy', usedIn: [] },
        'iron_ore': { name: 'Iron Ore', price: 24.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'bauxite_ore': { name: 'Bauxite Ore', price: 26.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'limestone': { name: 'Limestone', price: 14.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'gypsum': { name: 'Gypsum', price: 16.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'crude_oil': { name: 'Crude Oil', price: 36.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'minerals': { name: 'Minerals', price: 32.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'sand': { name: 'Sand', price: 8.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'clay': { name: 'Clay', price: 9.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'energy': { name: 'Energy', price: 0.90, category: 'Utilities', producedBy: 'Government', usedIn: ['Coal', 'Iron Ore', 'Bauxite Ore', 'Limestone', 'Gypsum', 'Crude Oil', 'Minerals', 'Sand', 'Clay'] },
        'cows': { name: 'Cows', price: 620.00, category: 'Agriculture', producedBy: 'Government', usedIn: ['Milk'] },
        'hens': { name: 'Hens', price: 31.00, category: 'Agriculture', producedBy: 'Government', usedIn: ['Eggs'] },
        'shirts': { name: 'Shirts', price: 68.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'jeans': { name: 'Jeans', price: 96.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'jackets': { name: 'Jackets', price: 160.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'fabric': { name: 'Fabric', price: 30.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'bread': { name: 'Bread', price: 48.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'biscuits': { name: 'Biscuits', price: 44.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'cheese': { name: 'Cheese', price: 72.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'steel': { name: 'Steel', price: 43.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: ['Steel Beams'] },
        'aluminium': { name: 'Aluminium', price: 45.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'cement': { name: 'Cement', price: 56.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'bricks': { name: 'Bricks', price: 36.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'steel_beams': { name: 'Steel Beams', price: 145.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: ['Cars'] },
        'glass': { name: 'Glass', price: 13.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'silicon': { name: 'Silicon', price: 16.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'plastics': { name: 'Plastics', price: 50.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'chemicals': { name: 'Chemicals', price: 46.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'processor': { name: 'Processor', price: 162.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs', 'On-board Computer'] },
        'display': { name: 'Display', price: 225.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs'] },
        'electronic_components': { name: 'Electronic Components', price: 135.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs', 'On-board Computer'] },
        'battery': { name: 'Battery', price: 198.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops'] },
        'on_board_computer': { name: 'On-board Computer', price: 765.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Cars'] },
        'phones': { name: 'Phones', price: 1450.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'laptops': { name: 'Laptops', price: 3850.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'tvs': { name: 'TVs', price: 2560.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'combustion_engine': { name: 'Combustion Engine', price: 1000.00, category: 'Automotive', producedBy: 'Automobile Manufacturing', usedIn: ['Cars'] },
        'cars': { name: 'Cars', price: 52000.00, category: 'Automotive', producedBy: 'Automobile Manufacturing', usedIn: [] }
      },
      construction: {},
      utilities: {},
      taxes: {}
    },
    'Japan': {
      currency: 'JPY',
      employees: {
        'Farmer': 280000,
        'Labourer': 250000,
        'Engineer': 700000,
        'Manager': 900000,
        'Chef': 400000,
        'Fashion Designer': 620000
      },
      commodities: {
        'seeds': { name: 'Seeds', price: 18, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Wheat', 'Rice', 'Cotton', 'Grains', 'Vegetables'] },
        'water': { name: 'Water', price: 6, category: 'Agriculture', producedBy: 'Government', usedIn: ['Seeds', 'Wheat', 'Rice', 'Cotton', 'Grains', 'Vegetables', 'Milk', 'Eggs'] },
        'wheat': { name: 'Wheat', price: 320, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Bread', 'Biscuits'] },
        'rice': { name: 'Rice', price: 300, category: 'Agriculture', producedBy: 'Farming', usedIn: [] },
        'cotton': { name: 'Cotton', price: 360, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Shirts', 'Jeans', 'Jackets'] },
        'milk': { name: 'Milk', price: 135, category: 'Agriculture', producedBy: 'Dairy', usedIn: ['Biscuits', 'Cheese'] },
        'coal': { name: 'Coal', price: 1200, category: 'Mining', producedBy: 'Mining', usedIn: ['Cement', 'Bricks', 'Steel Beams', 'Phones', 'Laptops', 'TVs', 'Cars'] },
        'grains': { name: 'Grains', price: 42, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Fodder', 'Eggs'] },
        'vegetables': { name: 'Vegetables', price: 72, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Fodder'] },
        'fodder': { name: 'Fodder', price: 64, category: 'Agriculture', producedBy: 'Dairy', usedIn: ['Milk'] },
        'eggs': { name: 'Eggs', price: 85, category: 'Agriculture', producedBy: 'Dairy', usedIn: [] },
        'iron_ore': { name: 'Iron Ore', price: 1000, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'bauxite_ore': { name: 'Bauxite Ore', price: 1100, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'limestone': { name: 'Limestone', price: 630, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'gypsum': { name: 'Gypsum', price: 700, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'crude_oil': { name: 'Crude Oil', price: 1600, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'minerals': { name: 'Minerals', price: 1400, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'sand': { name: 'Sand', price: 350, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'clay': { name: 'Clay', price: 410, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'energy': { name: 'Energy', price: 42, category: 'Utilities', producedBy: 'Government', usedIn: ['Coal', 'Iron Ore', 'Bauxite Ore', 'Limestone', 'Gypsum', 'Crude Oil', 'Minerals', 'Sand', 'Clay'] },
        'cows': { name: 'Cows', price: 28000, category: 'Agriculture', producedBy: 'Government', usedIn: ['Milk'] },
        'hens': { name: 'Hens', price: 1400, category: 'Agriculture', producedBy: 'Government', usedIn: ['Eggs'] },
        'shirts': { name: 'Shirts', price: 3000, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'jeans': { name: 'Jeans', price: 4200, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'jackets': { name: 'Jackets', price: 7000, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'fabric': { name: 'Fabric', price: 630, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'bread': { name: 'Bread', price: 2100, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'biscuits': { name: 'Biscuits', price: 1900, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'cheese': { name: 'Cheese', price: 3200, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'steel': { name: 'Steel', price: 900, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: ['Steel Beams'] },
        'aluminium': { name: 'Aluminium', price: 930, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'cement': { name: 'Cement', price: 2500, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'bricks': { name: 'Bricks', price: 1600, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'steel_beams': { name: 'Steel Beams', price: 6400, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: ['Cars'] },
        'glass': { name: 'Glass', price: 320, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'silicon': { name: 'Silicon', price: 390, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'plastics': { name: 'Plastics', price: 1100, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'chemicals': { name: 'Chemicals', price: 1000, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'processor': { name: 'Processor', price: 3200, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs', 'On-board Computer'] },
        'display': { name: 'Display', price: 4500, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs'] },
        'electronic_components': { name: 'Electronic Components', price: 2700, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs', 'On-board Computer'] },
        'battery': { name: 'Battery', price: 3900, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops'] },
        'on_board_computer': { name: 'On-board Computer', price: 15300, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Cars'] },
        'phones': { name: 'Phones', price: 64000, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'laptops': { name: 'Laptops', price: 170000, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'tvs': { name: 'TVs', price: 112000, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'combustion_engine': { name: 'Combustion Engine', price: 24000, category: 'Automotive', producedBy: 'Automobile Manufacturing', usedIn: ['Cars'] },
        'cars': { name: 'Cars', price: 2400000, category: 'Automotive', producedBy: 'Automobile Manufacturing', usedIn: [] }
      },
      construction: {},
      utilities: {},
      taxes: {}
    },
    'Australia': {
      currency: 'AUD',
      employees: {
        'Farmer': 5000,
        'Labourer': 4700,
        'Engineer': 9000,
        'Manager': 12000,
        'Chef': 5800,
        'Fashion Designer': 8200
      },
      commodities: {
        'seeds': { name: 'Seeds', price: 0.20, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Wheat', 'Rice', 'Cotton', 'Grains', 'Vegetables'] },
        'water': { name: 'Water', price: 0.07, category: 'Agriculture', producedBy: 'Government', usedIn: ['Seeds', 'Wheat', 'Rice', 'Cotton', 'Grains', 'Vegetables', 'Milk', 'Eggs'] },
        'wheat': { name: 'Wheat', price: 3.40, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Bread', 'Biscuits'] },
        'rice': { name: 'Rice', price: 3.20, category: 'Agriculture', producedBy: 'Farming', usedIn: [] },
        'cotton': { name: 'Cotton', price: 3.90, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Shirts', 'Jeans', 'Jackets'] },
        'milk': { name: 'Milk', price: 1.65, category: 'Agriculture', producedBy: 'Dairy', usedIn: ['Biscuits', 'Cheese'] },
        'coal': { name: 'Coal', price: 11.00, category: 'Mining', producedBy: 'Mining', usedIn: ['Cement', 'Bricks', 'Steel Beams', 'Phones', 'Laptops', 'TVs', 'Cars'] },
        'grains': { name: 'Grains', price: 0.50, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Fodder', 'Eggs'] },
        'vegetables': { name: 'Vegetables', price: 0.80, category: 'Agriculture', producedBy: 'Farming', usedIn: ['Fodder'] },
        'fodder': { name: 'Fodder', price: 0.70, category: 'Agriculture', producedBy: 'Dairy', usedIn: ['Milk'] },
        'eggs': { name: 'Eggs', price: 1.05, category: 'Agriculture', producedBy: 'Dairy', usedIn: [] },
        'iron_ore': { name: 'Iron Ore', price: 11.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'bauxite_ore': { name: 'Bauxite Ore', price: 12.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'limestone': { name: 'Limestone', price: 6.50, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'gypsum': { name: 'Gypsum', price: 7.50, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'crude_oil': { name: 'Crude Oil', price: 16.50, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'minerals': { name: 'Minerals', price: 15.00, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'sand': { name: 'Sand', price: 3.80, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'clay': { name: 'Clay', price: 3.30, category: 'Mining', producedBy: 'Mining', usedIn: [] },
        'energy': { name: 'Energy', price: 0.50, category: 'Utilities', producedBy: 'Government', usedIn: ['Coal', 'Iron Ore', 'Bauxite Ore', 'Limestone', 'Gypsum', 'Crude Oil', 'Minerals', 'Sand', 'Clay'] },
        'cows': { name: 'Cows', price: 330.00, category: 'Agriculture', producedBy: 'Government', usedIn: ['Milk'] },
        'hens': { name: 'Hens', price: 16.50, category: 'Agriculture', producedBy: 'Government', usedIn: ['Eggs'] },
        'shirts': { name: 'Shirts', price: 32.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'jeans': { name: 'Jeans', price: 48.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'jackets': { name: 'Jackets', price: 80.00, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'fabric': { name: 'Fabric', price: 13.50, category: 'Garments', producedBy: 'Garment Factory', usedIn: [] },
        'bread': { name: 'Bread', price: 21.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'biscuits': { name: 'Biscuits', price: 20.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'cheese': { name: 'Cheese', price: 34.00, category: 'Food Processing', producedBy: 'Food Processing Factory', usedIn: [] },
        'steel': { name: 'Steel', price: 19.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: ['Steel Beams'] },
        'aluminium': { name: 'Aluminium', price: 20.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'cement': { name: 'Cement', price: 27.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'bricks': { name: 'Bricks', price: 17.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'steel_beams': { name: 'Steel Beams', price: 70.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: ['Cars'] },
        'glass': { name: 'Glass', price: 6.50, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'silicon': { name: 'Silicon', price: 8.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'plastics': { name: 'Plastics', price: 22.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'chemicals': { name: 'Chemicals', price: 20.00, category: 'Construction Materials', producedBy: 'Construction Factory', usedIn: [] },
        'processor': { name: 'Processor', price: 68.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs', 'On-board Computer'] },
        'display': { name: 'Display', price: 95.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs'] },
        'electronic_components': { name: 'Electronic Components', price: 57.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops', 'TVs', 'On-board Computer'] },
        'battery': { name: 'Battery', price: 83.50, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Phones', 'Laptops'] },
        'on_board_computer': { name: 'On-board Computer', price: 323.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: ['Cars'] },
        'phones': { name: 'Phones', price: 700.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'laptops': { name: 'Laptops', price: 1820.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'tvs': { name: 'TVs', price: 1220.00, category: 'Electronics', producedBy: 'Electronics Manufacturing', usedIn: [] },
        'combustion_engine': { name: 'Combustion Engine', price: 500.00, category: 'Automotive', producedBy: 'Automobile Manufacturing', usedIn: ['Cars'] },
        'cars': { name: 'Cars', price: 25000.00, category: 'Automotive', producedBy: 'Automobile Manufacturing', usedIn: [] }
      },
      construction: {},
      utilities: {},
      taxes: {}
    }
  }
};

/**
 * Get salary for a specific employee type in a given country
 * @param {string} country 
 * @param {string} employeeType 
 * @returns {number}
 */
export function getSalary(country, employeeType) {
  let normalizedType = employeeType;
  if (employeeType === 'Chief') {
    normalizedType = 'Chef';
  }
  const countryData = countryEconomy.countries[country] || countryEconomy.countries['United States'];
  return countryData.employees[normalizedType] || 1000;
}

/**
 * Get local price for a specific product in a given country
 * @param {string} country 
 * @param {string} productId 
 * @returns {number}
 */
export function getProductPrice(country, productId) {
  const countryData = countryEconomy.countries[country] || countryEconomy.countries['United States'];
  const commodity = countryData.commodities[productId] || {};
  return commodity.price || 10;
}

export default countryEconomy;
